include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    # Paket public API'sindeki üyelerin doc comment'i olmasını zorunlu kıl
    public_member_api_docs: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # ── Style ──
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_decorated_box: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    prefer_relative_imports: false

    # ── Safety ──
    always_declare_return_types: true
    avoid_print: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_dynamic_calls: true
    unawaited_futures: true
    discarded_futures: true

    # ── Doc (pub.dev için public API doc önerilir) ──
    public_member_api_docs: false  # true yaparak katı moda alınabilir

    # ── Performans & Temizlik ──
    avoid_slow_async_io: true
    prefer_void_to_null: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true

    # ── Disabled (aşırı katı olmasın) ──
    always_specify_types: false
    lines_longer_than_80_chars: false
